import {
  ReferenceItem,
  ReferenceType,
  ArticleMetadata,
  HearingMetadata,
  LegalCaseMetadata,
  LegislationMetadata,
  ConferencePaperMetadata,
  ThesisMetadata,
  RegulationMetadata,
  ReportMetadata,
  BillMetadata,
  BookMetadata,
  GeneralDocumentMetadata,
} from '@/types/reference-manager';
interface FieldConfig {
  label: string;
  key: string;
  isTextarea?: boolean;
}

export const allIconNames = [
  'folder',
  'folder-plus',
  'folder-open',
  'folder-minus',
  'file',
  'file-text',
  'file-plus',
  'file-check',
  'file-pen', // renamed from file-edit
  'file-search',
  'file-output',
  'file-code',
  'file-image',
  'file-video-camera', // renamed from file-video (closest match)
  'file-audio',
  'pen', // renamed from edit-2
  'pencil', // renamed from edit
  'settings',
  'cog',
  'sliders-horizontal',
  'shield',
  'shield-check',
  'shield-alert',
  'star',
  'star-half',
  'star-off',
  'heart',
  'heart-crack',
  'heart-off',
  'image',
  'camera',
  'camera-off',
  'video',
  'video-off',
  'download',
  'upload',
  'cloud-upload', // renamed from upload-cloud
  'cloud-download', // renamed from download-cloud
  'bell',
  'bell-off',
  'calendar',
  'calendar-check',
  'calendar-plus',
  'calendar-days',
  'archive',
  'tag',
  'tags',
  'users',
  'user',
  'user-plus',
  'user-minus',
  'circle-user', // renamed from user-circle
  'user-cog',
  'house', // renamed from home
  'house-plus',
  // "house-heart", // removed as it seems missing
  'mail',
  'mail-plus',
  'mail-open',
  'search',
  'search-check',
  'search-code',
  'search-slash',
  'plus',
  'minus',
  'x',
  'check',
  'trash',
  'trash-2',
  'book',
  'book-open',
  'book-open-text',
  'bookmark',
  'bookmark-plus',
  'flag',
  'list-filter', // renamed from filter
  // "filter-x", // removed as it seems missing
  'hash',
  'link',
  'link-2',
  'link-2-off',
  'globe',
  'globe-lock',
  'wifi',
  'wifi-off',
  'bluetooth',
  'bluetooth-off',
  'map',
  'map-pin',
  'map-pinned',
  'pin',
  'pin-off',
  'message-circle',
  'message-square',
  'messages-square',
  'comment',
  'copy',
  'copy-plus',
  'clipboard',
  'clipboard-list',
  'clipboard-check',
  'key',
  'lock',
  'unlock',
  'log-in',
  'log-out',
  'moon',
  'sun',
  'cloud',
  'cloud-rain',
  'cloud-sun',
  'cloud-snow',
  'alert-circle',
  'alert-triangle',
  'info',
  'help-circle',
  'refresh-cw',
  'refresh-ccw',
  'rotate-ccw',
  'rotate-cw',
  'loader',
  'ellipsis',
  'menu',
  'more-horizontal',
  'more-vertical',
];

// Info tab fields - file information (not type-specific)
export const infoFields: FieldConfig[] = [
  { label: 'File name', key: 'fileName' },
  { label: 'Uploaded by', key: 'uploadedBy' },
  { label: 'Location', key: 'location' },
];

// Property fields by reference type
export const propertyFieldsByType: Record<ReferenceType, FieldConfig[]> = {
  article: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Call number', key: 'callNumber' },
    { label: 'Date', key: 'date' },
    { label: 'Genre', key: 'genre' },
    { label: 'Language', key: 'language' },
    { label: 'Publisher', key: 'publisher' },
    { label: 'Publisher place', key: 'publisherPlace' },
    { label: 'License', key: 'license' },
    { label: 'Publication', key: 'publication' },
    { label: 'Series', key: 'series' },
    { label: 'Series number', key: 'seriesNumber' },
  ],
  hearing: [
    { label: 'Contributor', key: 'contributor' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Date', key: 'date' },
    { label: 'Language', key: 'language' },
    { label: 'History', key: 'history' },
    { label: 'Legislative body', key: 'legislativeBody' },
    { label: 'Committee', key: 'committee' },
    { label: 'Publisher', key: 'publisher' },
    { label: 'License', key: 'license' },
    { label: 'Place', key: 'place' },
    { label: 'Document number', key: 'documentNumber' },
    { label: 'No. of volumes', key: 'numberOfVolumes' },
    { label: 'Pages', key: 'pages' },
    { label: 'Session', key: 'session' },
  ],
  legal_case: [
    { label: 'Author', key: 'author' },
    { label: 'Case name', key: 'caseName' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Docket number', key: 'docketNumber' },
    { label: 'Date decided', key: 'dateDecided' },
    { label: 'Language', key: 'language' },
    { label: 'History', key: 'history' },
    { label: 'Court', key: 'court' },
    { label: 'Reporter', key: 'reporter' },
    { label: 'Report volume', key: 'reportVolume' },
    { label: 'License', key: 'license' },
    { label: 'Pages', key: 'pages' },
  ],
  legislation: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Date enacted', key: 'dateEnacted' },
    { label: 'Language', key: 'language' },
    { label: 'History', key: 'history' },
    { label: 'Legislative body', key: 'legislativeBody' },
    { label: 'License', key: 'license' },
    { label: 'Code', key: 'code' },
    { label: 'Code volume', key: 'codeVolume' },
    { label: 'Pages', key: 'pages' },
    { label: 'Section', key: 'section' },
    { label: 'Session', key: 'session' },
    { label: 'Law number', key: 'lawNumber' },
  ],
  conference_paper: [
    { label: 'Author', key: 'author' },
    { label: 'Conference name', key: 'conferenceName' },
    { label: 'Proceeding title', key: 'proceedingTitle' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Call number', key: 'callNumber' },
    { label: 'Date', key: 'date' },
    { label: 'Conference place', key: 'conferencePlace' },
    { label: 'Language', key: 'language' },
    { label: 'Publisher', key: 'publisher' },
    { label: 'Publisher place', key: 'publisherPlace' },
    { label: 'License', key: 'license' },
    { label: 'Series', key: 'series' },
    { label: 'Volume', key: 'volume' },
    { label: 'Page', key: 'page' },
  ],
  thesis: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Type', key: 'type' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Call number', key: 'callNumber' },
    { label: 'Date', key: 'date' },
    { label: 'Language', key: 'language' },
    { label: 'University', key: 'university' },
    { label: 'Place', key: 'place' },
    { label: 'License', key: 'license' },
    { label: 'No. of pages', key: 'numberOfPages' },
  ],
  regulation: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Enforcement date', key: 'enforcementDate' },
    { label: 'Language', key: 'language' },
    { label: 'Legislation', key: 'legislation' },
    { label: 'Government body', key: 'governmentBody' },
    { label: 'License', key: 'license' },
    { label: 'Code', key: 'code' },
    { label: 'Code volume', key: 'codeVolume' },
    { label: 'Pages', key: 'pages' },
    { label: 'Section', key: 'section' },
    { label: 'Session', key: 'session' },
    { label: 'Regulation number', key: 'regulationNumber' },
  ],
  report: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Report type', key: 'reportType' },
    { label: 'Report number', key: 'reportNumber' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Call number', key: 'callNumber' },
    { label: 'Date', key: 'date' },
    { label: 'Language', key: 'language' },
    { label: 'Institution', key: 'institution' },
    { label: 'Place', key: 'place' },
    { label: 'License', key: 'license' },
    { label: 'Series', key: 'series' },
  ],
  bill: [
    { label: 'Sponsor', key: 'sponsor' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Date', key: 'date' },
    { label: 'Language', key: 'language' },
    { label: 'History', key: 'history' },
    { label: 'Legislative body', key: 'legislativeBody' },
    { label: 'License', key: 'license' },
    { label: 'Code', key: 'code' },
    { label: 'Code pages', key: 'codePages' },
    { label: 'Code volume', key: 'codeVolume' },
    { label: 'Section', key: 'section' },
    { label: 'Session', key: 'session' },
  ],
  book: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Call number', key: 'callNumber' },
    { label: 'Date', key: 'date' },
    { label: 'Note', key: 'note' },
    { label: 'Language', key: 'language' },
    { label: 'Publisher', key: 'publisher' },
    { label: 'Publisher place', key: 'publisherPlace' },
    { label: 'License', key: 'license' },
    { label: 'Edition', key: 'edition' },
    { label: 'Series', key: 'series' },
    { label: 'Series number', key: 'seriesNumber' },
    { label: 'No. of volumes', key: 'numberOfVolumes' },
    { label: 'Volume', key: 'volume' },
    { label: 'No. of pages', key: 'numberOfPages' },
  ],
  general_document: [
    { label: 'Author', key: 'author' },
    { label: 'URL', key: 'url' },
    { label: 'Format', key: 'format' },
    { label: 'Abstract', key: 'abstract', isTextarea: true },
    { label: 'Call number', key: 'callNumber' },
    { label: 'Date', key: 'date' },
    { label: 'Language', key: 'language' },
    { label: 'Publisher', key: 'publisher' },
    { label: 'Publisher place', key: 'publisherPlace' },
    { label: 'License', key: 'license' },
  ],
};
